# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/watrix/mytest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/watrix/mytest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/watrix/mytest/CMakeFiles /home/watrix/mytest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/watrix/mytest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named facedemo

# Build rule for target.
facedemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 facedemo
.PHONY : facedemo

# fast build rule for target.
facedemo/fast:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/build
.PHONY : facedemo/fast

src/common/common1.o: src/common/common1.cpp.o

.PHONY : src/common/common1.o

# target to build an object file
src/common/common1.cpp.o:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/common/common1.cpp.o
.PHONY : src/common/common1.cpp.o

src/common/common1.i: src/common/common1.cpp.i

.PHONY : src/common/common1.i

# target to preprocess a source file
src/common/common1.cpp.i:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/common/common1.cpp.i
.PHONY : src/common/common1.cpp.i

src/common/common1.s: src/common/common1.cpp.s

.PHONY : src/common/common1.s

# target to generate assembly for a file
src/common/common1.cpp.s:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/common/common1.cpp.s
.PHONY : src/common/common1.cpp.s

src/driver/face_align.o: src/driver/face_align.cpp.o

.PHONY : src/driver/face_align.o

# target to build an object file
src/driver/face_align.cpp.o:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/face_align.cpp.o
.PHONY : src/driver/face_align.cpp.o

src/driver/face_align.i: src/driver/face_align.cpp.i

.PHONY : src/driver/face_align.i

# target to preprocess a source file
src/driver/face_align.cpp.i:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/face_align.cpp.i
.PHONY : src/driver/face_align.cpp.i

src/driver/face_align.s: src/driver/face_align.cpp.s

.PHONY : src/driver/face_align.s

# target to generate assembly for a file
src/driver/face_align.cpp.s:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/face_align.cpp.s
.PHONY : src/driver/face_align.cpp.s

src/driver/feature_extractor.o: src/driver/feature_extractor.cpp.o

.PHONY : src/driver/feature_extractor.o

# target to build an object file
src/driver/feature_extractor.cpp.o:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/feature_extractor.cpp.o
.PHONY : src/driver/feature_extractor.cpp.o

src/driver/feature_extractor.i: src/driver/feature_extractor.cpp.i

.PHONY : src/driver/feature_extractor.i

# target to preprocess a source file
src/driver/feature_extractor.cpp.i:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/feature_extractor.cpp.i
.PHONY : src/driver/feature_extractor.cpp.i

src/driver/feature_extractor.s: src/driver/feature_extractor.cpp.s

.PHONY : src/driver/feature_extractor.s

# target to generate assembly for a file
src/driver/feature_extractor.cpp.s:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/feature_extractor.cpp.s
.PHONY : src/driver/feature_extractor.cpp.s

src/driver/get_face.o: src/driver/get_face.cpp.o

.PHONY : src/driver/get_face.o

# target to build an object file
src/driver/get_face.cpp.o:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/get_face.cpp.o
.PHONY : src/driver/get_face.cpp.o

src/driver/get_face.i: src/driver/get_face.cpp.i

.PHONY : src/driver/get_face.i

# target to preprocess a source file
src/driver/get_face.cpp.i:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/get_face.cpp.i
.PHONY : src/driver/get_face.cpp.i

src/driver/get_face.s: src/driver/get_face.cpp.s

.PHONY : src/driver/get_face.s

# target to generate assembly for a file
src/driver/get_face.cpp.s:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/get_face.cpp.s
.PHONY : src/driver/get_face.cpp.s

src/driver/lightened_cnn.o: src/driver/lightened_cnn.cpp.o

.PHONY : src/driver/lightened_cnn.o

# target to build an object file
src/driver/lightened_cnn.cpp.o:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/lightened_cnn.cpp.o
.PHONY : src/driver/lightened_cnn.cpp.o

src/driver/lightened_cnn.i: src/driver/lightened_cnn.cpp.i

.PHONY : src/driver/lightened_cnn.i

# target to preprocess a source file
src/driver/lightened_cnn.cpp.i:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/lightened_cnn.cpp.i
.PHONY : src/driver/lightened_cnn.cpp.i

src/driver/lightened_cnn.s: src/driver/lightened_cnn.cpp.s

.PHONY : src/driver/lightened_cnn.s

# target to generate assembly for a file
src/driver/lightened_cnn.cpp.s:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/lightened_cnn.cpp.s
.PHONY : src/driver/lightened_cnn.cpp.s

src/driver/mtcnn.o: src/driver/mtcnn.cpp.o

.PHONY : src/driver/mtcnn.o

# target to build an object file
src/driver/mtcnn.cpp.o:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/mtcnn.cpp.o
.PHONY : src/driver/mtcnn.cpp.o

src/driver/mtcnn.i: src/driver/mtcnn.cpp.i

.PHONY : src/driver/mtcnn.i

# target to preprocess a source file
src/driver/mtcnn.cpp.i:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/mtcnn.cpp.i
.PHONY : src/driver/mtcnn.cpp.i

src/driver/mtcnn.s: src/driver/mtcnn.cpp.s

.PHONY : src/driver/mtcnn.s

# target to generate assembly for a file
src/driver/mtcnn.cpp.s:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/mtcnn.cpp.s
.PHONY : src/driver/mtcnn.cpp.s

src/driver/mtcnn_utils.o: src/driver/mtcnn_utils.cpp.o

.PHONY : src/driver/mtcnn_utils.o

# target to build an object file
src/driver/mtcnn_utils.cpp.o:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/mtcnn_utils.cpp.o
.PHONY : src/driver/mtcnn_utils.cpp.o

src/driver/mtcnn_utils.i: src/driver/mtcnn_utils.cpp.i

.PHONY : src/driver/mtcnn_utils.i

# target to preprocess a source file
src/driver/mtcnn_utils.cpp.i:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/mtcnn_utils.cpp.i
.PHONY : src/driver/mtcnn_utils.cpp.i

src/driver/mtcnn_utils.s: src/driver/mtcnn_utils.cpp.s

.PHONY : src/driver/mtcnn_utils.s

# target to generate assembly for a file
src/driver/mtcnn_utils.cpp.s:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/mtcnn_utils.cpp.s
.PHONY : src/driver/mtcnn_utils.cpp.s

src/driver/scale_angle.o: src/driver/scale_angle.cpp.o

.PHONY : src/driver/scale_angle.o

# target to build an object file
src/driver/scale_angle.cpp.o:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/scale_angle.cpp.o
.PHONY : src/driver/scale_angle.cpp.o

src/driver/scale_angle.i: src/driver/scale_angle.cpp.i

.PHONY : src/driver/scale_angle.i

# target to preprocess a source file
src/driver/scale_angle.cpp.i:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/scale_angle.cpp.i
.PHONY : src/driver/scale_angle.cpp.i

src/driver/scale_angle.s: src/driver/scale_angle.cpp.s

.PHONY : src/driver/scale_angle.s

# target to generate assembly for a file
src/driver/scale_angle.cpp.s:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/scale_angle.cpp.s
.PHONY : src/driver/scale_angle.cpp.s

src/driver/svd.o: src/driver/svd.cpp.o

.PHONY : src/driver/svd.o

# target to build an object file
src/driver/svd.cpp.o:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/svd.cpp.o
.PHONY : src/driver/svd.cpp.o

src/driver/svd.i: src/driver/svd.cpp.i

.PHONY : src/driver/svd.i

# target to preprocess a source file
src/driver/svd.cpp.i:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/svd.cpp.i
.PHONY : src/driver/svd.cpp.i

src/driver/svd.s: src/driver/svd.cpp.s

.PHONY : src/driver/svd.s

# target to generate assembly for a file
src/driver/svd.cpp.s:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/driver/svd.cpp.s
.PHONY : src/driver/svd.cpp.s

src/faceID.o: src/faceID.cpp.o

.PHONY : src/faceID.o

# target to build an object file
src/faceID.cpp.o:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/faceID.cpp.o
.PHONY : src/faceID.cpp.o

src/faceID.i: src/faceID.cpp.i

.PHONY : src/faceID.i

# target to preprocess a source file
src/faceID.cpp.i:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/faceID.cpp.i
.PHONY : src/faceID.cpp.i

src/faceID.s: src/faceID.cpp.s

.PHONY : src/faceID.s

# target to generate assembly for a file
src/faceID.cpp.s:
	$(MAKE) -f CMakeFiles/facedemo.dir/build.make CMakeFiles/facedemo.dir/src/faceID.cpp.s
.PHONY : src/faceID.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... facedemo"
	@echo "... src/common/common1.o"
	@echo "... src/common/common1.i"
	@echo "... src/common/common1.s"
	@echo "... src/driver/face_align.o"
	@echo "... src/driver/face_align.i"
	@echo "... src/driver/face_align.s"
	@echo "... src/driver/feature_extractor.o"
	@echo "... src/driver/feature_extractor.i"
	@echo "... src/driver/feature_extractor.s"
	@echo "... src/driver/get_face.o"
	@echo "... src/driver/get_face.i"
	@echo "... src/driver/get_face.s"
	@echo "... src/driver/lightened_cnn.o"
	@echo "... src/driver/lightened_cnn.i"
	@echo "... src/driver/lightened_cnn.s"
	@echo "... src/driver/mtcnn.o"
	@echo "... src/driver/mtcnn.i"
	@echo "... src/driver/mtcnn.s"
	@echo "... src/driver/mtcnn_utils.o"
	@echo "... src/driver/mtcnn_utils.i"
	@echo "... src/driver/mtcnn_utils.s"
	@echo "... src/driver/scale_angle.o"
	@echo "... src/driver/scale_angle.i"
	@echo "... src/driver/scale_angle.s"
	@echo "... src/driver/svd.o"
	@echo "... src/driver/svd.i"
	@echo "... src/driver/svd.s"
	@echo "... src/faceID.o"
	@echo "... src/faceID.i"
	@echo "... src/faceID.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

